[project]
name = "ScalingElections"
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]
description = "GPU-accelerated Schulze voting algorithm in Mojo 🔥"

[dependencies]
python = "3.12.*"
max = ">=25.6.1,<26"
