[project]
name = "ScalingDemocracy"
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]
description = "Mojo implementation of the Schulze voting algorithm"

[dependencies]
python = "3.12.*"
max = ">=25.6.1,<26"
